name: Popo story art and blog
description: unproductive mistakes
meta_description: "Kevin Hsieh blog featuring art and writing"

aboutPage: true

markdown: kramdown
highlighter: rouge

paginate: 1
baseurl: https://kvnhsh.github.io/
domain_name: 'http://yourblog-domain.com'
google_analytics: 'UA-XXXXXXXX-X'
disqus: true
disqus_shortname: 'popostoryartandblog'

# Details for the RSS feed generator
url:            'https://kvnhsh.github.io/'
author:         'Kevin Hsieh'
authorTwitter:  'YourTwitterUsername'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
